name: Java Build and Test with Maven

on:
  pull_request:
    branches: [master]

  jobs:
    test:
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - uses: actions/checkout@v4
        - name: Setup JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
        - name: Setup Maven
          uses: maven/actions/setup-maven@v4
        - name: Change wrapper permissions
          run: chmod +x ./mvnw
        - name: Run tests
          run: ./mvnw test

    build:
      needs: test
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - uses: actions/checkout@v4
        - name: Setup JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
        - name: Setup Maven
          uses: maven/actions/setup-maven@v4
        - name: Change wrapper permissions
          run: chmod +x ./mvnw
        - name: Build application
          run: ./mvnw package