name: Java Build and Test with Maven

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      LC_ALL: "en_US.UTF-8"
      LANG: "en_US.UTF-8"
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run tests
        run: mvn -B test --file pom.xml

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      LC_ALL: "en_US.UTF-8"
      LANG: "en_US.UTF-8"
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build application
        run: mvn -B package --file pom.xml